### ISSUE TITLE
Linker errors with CAENVMELib 3.3.0

### ISSUE THREAD

**Issue by swertz** [delaere/VeheMencE#21]
I have linker errors using the latest version of CAENVMELib: `undefined reference to CAENVME_DecodeError`. The linking works fine if I comment this function in `CommonDef.h`. Running `nm -gDC lib/x64/libCAENVME.so.3.3.0` does not show `CAENVME_DecodeError`, so it really looks like that function definition is missing from that build... although the declaration is present in `include/CAENVMElib.h`.

I've opened a ticket with CAEN support, but I was wondering which version has been used in the past that compiled correctly...?

**Comment by delaere** [comment]
On my machine I have libCAENVME.so.2.50, but I don't know what version was used on the PC used for testing with the VME crate in the electronics lab. It is probably the same since the timestamp matches (mid 2019)

**Comment by swertz** [comment]
Thanks, I confirm that it works fine with 2.5.0, using the package from EPEL.

**Comment by swertz** [comment]
A new version with the bug fixed is now available from the CAEN website: 3.99.3
